In [1]:
import numpy as np

# bruteforce

In [2]:
def diff1(l1,l2):
    """если строки отличаются в одной позиции - возвращает ёё иначе -1"""
    p = -1;
    for i in range(len(l1)):
        if l1[i]!=l2[i]:
            if p==-1:
                p = i
            else:
                return -1
    return p
def check(matrix, line):
    """
    проверяет, что сама line отсутствует, 
    ищет позиции в которых отличается от строк ровно на 1 символ
    и чтобы в каждой позиции была такая позиция
    """
    pos = set()
    for i in range(len(matrix)):
        if (line==matrix[i]).all():
            return False
        p = diff1(line,matrix[i])
        if p!=-1:
            pos.add(p)
    ret =  len(pos)==len(matrix[0])
    #print('check',matrix,line,ret)
    return ret
        
    

In [3]:
def subsets(base,n,res):
    if n==1:
        for i in range(len(base)):
            res[-n] = base[i]
            yield res
    else:
        for i in range(len(base)-n+1):
            for q in subsets(base[i+1:],n-1,res):
                assert q is res
                res[-n] = base[i]
                yield res

In [4]:
n = 5
base=[x for x in range(n)]
for i in range(n-1):
    res=[-1 for x in range(i+1)]
    for res in subsets(base,i+1,res):
        print(res)

[0]
[1]
[2]
[3]
[4]
[0, 1]
[0, 2]
[0, 3]
[0, 4]
[1, 2]
[1, 3]
[1, 4]
[2, 3]
[2, 4]
[3, 4]
[0, 1, 2]
[0, 1, 3]
[0, 1, 4]
[0, 2, 3]
[0, 2, 4]
[0, 3, 4]
[1, 2, 3]
[1, 2, 4]
[1, 3, 4]
[2, 3, 4]
[0, 1, 2, 3]
[0, 1, 2, 4]
[0, 1, 3, 4]
[0, 2, 3, 4]
[1, 2, 3, 4]


In [5]:
def number_of_patterns1(matrix) -> int:
    if type(matrix[0,0]) is not np.int32:
        print(type(matrix[0,0]))
    cnt = 0
    W = len(matrix[0])
    H = len(matrix)
    for i in range(W):
        if len(set(matrix[:,i]))==1:
            cnt+=1
            s = ['.']*W
            s[i] = str(int(not(bool(matrix[0,i]))))
            #print(''.join(s))
    base = [i for i in range(W)]
    for l in range(2,W+1):
        #print('l=',l)#,matrix,type(matrix),type(matrix[0,0]))
        ind = [i for i in range(l)]
        for ind in subsets(base,l,ind):
            submat = matrix[:,ind]
            #print('  ind=',ind,submat,type(submat[0,0]))
            lns = set()
            for line in submat:
                #print('    line=',line)
                for k in range(len(ind)):
                    ln = line.copy()
                    ln[k] = int(not(bool(line[k])))
                    if tuple(ln) in lns:
                        continue
                    else:
                        lns.add(tuple(ln))
                    if check(submat,ln):
                        cnt+=1
                        s = ['.']*W
                        #print(''.join(s))
                        for j in range(len(ind)):
                            s[ind[j]] = str(line[j])
                        #print(''.join(s))
                        s[ind[k]] = str(int(not(bool(line[k]))))
                        #print(''.join(s))
                        #print()
    return cnt

In [6]:
number_of_patterns1(np.array([[0,0],[1,1]]))

2

In [7]:
number_of_patterns1(np.array([[0,0],[1,1],[0,1]]))

1

In [8]:
number_of_patterns1(np.array(
    [[0,1,1,0],
[1,1,1,1],
[0,0,0,1]]))

9

In [9]:
n = 10
number_of_patterns1(np.eye(n,dtype=np.int32)) - 1 - n*(n-1)//2

0

In [10]:
number_of_patterns1(np.array(
[[0,0,0],
 [1,1,1],
 [1,1,0],
 [1,0,1]]))

3

In [11]:
n=10
m = np.eye(n,dtype=np.int32)
m[0] = np.zeros(n)+1
#print(m)
number_of_patterns1(m)

298

In [12]:
n = 10
print(n*(n-1)//2+1)
m = np.zeros((n*(n-1)//2+1,n+1),dtype=np.int32)
m[0] = np.zeros(n+1)+1
cnt=1
for i in range(n):
    for j in range(i+1,n):
        m[cnt,i+1]=1
        m[cnt,j+1]=1
        #print(m[cnt])
        cnt+=1
print('---\n',m)
number_of_patterns1(m)

46
---
 [[1 1 1 1 1 1 1 1 1 1 1]
 [0 1 1 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0 0 0 1]
 [0 0 1 1 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 1]
 [0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 1]
 [0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 1 0

980

# matrix incedence

In [13]:
import numpy as np

# я закономерность буду называть центральностью

# чтобы получить центральность необходимо в некоторой строке изменить один бит
# если строка x отличается от строки y одним битом, то изменением этого бита в строке x центральность получить невозможно
# центральность будем обозначать строкой, состоящей из '.', '0', '1' (точки и биты)
# при изменении любого бита (0<->1) в центральности мы должны получить паттерн (на строку), присутствующий в матрице
# если из строки x можно добраться в строку y изменив биты k,l, а строки x,y отличаются битами k,l,m_i, то биты m_i отсутствуют в центральности

# все множества не превышают 100 элементов, поэтому будем их хранить в целых числах как битовые множества

# матрица расстояний показывает, какие биты надо изменить, чтобы одна строка превратилась в другую
# в каждой строке пытемся изменить каждый бит
# найденные центральности складываем в общее множество
# далее алгоритм:
# 
# строку-бит задали (рассматриваем столбец в матрице расстояний, соответствующий данной строке. Он состоит из множеств)
# выбираем строки, в которых этот бит присутствует
#   в каждом множестве исключаем этот бит
# 
# среди выбранных
#   если есть пустые множества - конец (в эту строку можно добраться изменив только один бит)
#   если есть множества из одного элемента - фиксируем их (в эти строки можно добраться единственным способом)
#   из выбранных строк исключаем те, в которых присутствуют фиксированные элементы (они точно не равны центральности)
#   если строк не осталось - yield (найденные центральности складываем в общее множество)
# 
#   объединяем все множества выбранных строк
#   по каждому элементу из этого множества
#       по каждой из выбранных строк, в которой присутствует этот элемент
#           фиксируем этот элемент, а остальные элементы из этой строки добавляем в исключённые (точно должны отсутствовать в центральности)
#           из множеств удаляем исключённые
# 
#           если есть пустые множества - конец (в эту строку можно добраться изменив только один бит)
#           если есть множества из одного элемента - фиксируем их (в эти строки можно добраться единственным способом)
#           из выбранных строк исключаем те, в которых присутствуют выбранные элементы (они точно не равны центральности)
# 
#           если строк не осталось - yield (найденные центральности складываем в общее множество)
#           -> объединяем все множества выбранных строк (рекурсия)
# 
# + в алгоритм добавляем опитимизации, чтобы он не пытался добраться из текущей строки в ранее полностью рассмотренные
# ответ - размер общего множества центральностей + количество постоянных столбцов (которые мы в самом начале исключили)

from inspect import getframeinfo, stack

def thisline(message):
    caller = getframeinfo(stack()[1][0])
    return caller.lineno

def bits(x,l):
    s = ''
    for i in range(l):
        s+= '1' if (2**i)&x else '0'
    return s
def sets(x):
    se = set()
    i=0
    q=1
    while q<=x:
        if q&x:
            se.add(i)
        i+=1
        q<<=1
    return ''.join(str(i) for i in sorted(list(se)))
0.5 # статистику считать но не печатать
d_stat = 1 # 1 статистика
1.5 # только добавления
d_main = 2 # 2 основное
2.5 # + ускорения (пропуски)
d_dbg = 3 # 3 отладка
debug = 0
def printmat(m):
    ml = 0
    for i in range(len(m)):
        for j in range(len(m[i])):
            ml = max(ml,len(sets(m[i][j])))
    f = '{:'+str(ml)+'}'
    for i in range(len(m)):
        for j in range(len(m[i])):
            print(f.format(sets(m[i][j])),end=' ')
        print()
def print_sets2(sets,depth=0):
    union = 0
    for k,s in sets.items():
        union|= s
    se = set()
    i=0
    q=1
    while q<=union:
        if q&union:
            se.add(i)
        i+=1
        q<<=1
    se = sorted(list(se))
    for n,s in sets.items():
        print('    '*depth,f'{n:2}',')',end=' ')
        for i in se:
            print(i if (2**i)&s else ' ' if i<10 else '  ',end=' ')
        print()


def pc(fixed,center,W):
    fixed = bits(fixed,W)
    center = bits(center,W)
    s = ''
    for i in range(len(fixed)):
        s+= '.' if fixed[i]=='0' else center[i]
    return s
def number_of_patterns2(matrix1: np.ndarray) -> int:
    # одинаковые строки убираем сразу
    # постоянные столбцы обрабатываем отдельно и убираем
    cnt = 0
    W = len(matrix1[0])
    H = len(matrix1)
    # ищем постоянные столбцы
    matrix = [[] for i in range(H)]
    for i in range(W):
        if (matrix1[:,i]==1).all() or (matrix1[:,i]==0).all():
            cnt+=1
        else:
            for j in range(H):
                matrix[j].append(matrix1[j,i])
    W-=cnt
    if debug>=d_main: print('постоянных столбцов: ',cnt)
    
    # преобразовываем в биты
    for i in range(H):
        q=1
        line = 0
        for j in range(W):
            if matrix[i][j]:
                line|=q
            q<<=1
        matrix[i] = line
    all1 = 2**(W+1)-1

    # удаляем повторы
    matrix.sort()
    for i in range(H-2,-1,-1):
        if matrix[i]==matrix[i+1]:
            del matrix[i+1]
            H-=1
    if debug>=d_main: 
        print('подготовили матрицу',H,W)
        for x in matrix:
            print(bits(x,W))

    dist = []
    for i in range(H):
        dist.append([])
        for j in range(H):
            dist[i].append(matrix[i]^matrix[j])
    if debug>=d_stat+0.5: 
        print('матрица расстояний')
        printmat(dist)

    def count(x):
        q = 1
        cnt = 0
        while q<=x:
            if q&x:
                cnt+=1
            q<<=1
        return cnt
    centrals = set()
    maxdepth = 0
    falsecnt = 0
    for ln in range(H):
        if debug>=d_stat+0.5: print('---------',ln,'--------','//',len(centrals),falsecnt)
        for bn in range(W):
            bit = 2**bn
            # строку-бит задали

            # выбираем строки, в которых этот бит присутствует
            cur = {}
            cont = False
            fixed = 0
            for i in range(H):
                if dist[ln][i]&bit:
                    # в каждом множестве исключаем этот бит
                    cur[i] = dist[ln][i]^bit
                    # среди выбранных:
                    # если есть пустые множества - конец
                    if cur[i]==0:
                        if debug>=d_main+0.5: print(bn,'->',f'>>> {ln} void')
                        cont = True
                        break
                    # если есть множества из одного элемента - фиксируем их
                    if count(cur[i])==1:
                        if i<=ln: # в предыдущие строки нам не нужно попадать
                            if debug>=d_main+0.5: print(bn,'->',f'>>> {i} already done')
                            cont = True
                            break
                        fixed|=cur[i]
            if cont:
                continue
            if debug>=d_stat+0.5: print(bn,'->',sets(fixed),'//',len(centrals),falsecnt)

            # из выбранных строк исключаем те, в которых присутствуют фиксированные элементы
            cur = {k:v for k,v in cur.items() if v&fixed==0}
            #если строк не осталось - yield
            if len(cur)==0:
                fixed |= bit
                center = (matrix[ln]^bit)&fixed
                if debug>=0.5: 
                    boo = (fixed,center) in centrals
                    if boo: falsecnt+=1
                centrals.add((fixed,center))

                if debug>=d_stat+0.5:
                    print('+',pc(fixed,center,W),f'[{len(centrals)}]',end=' ')
                    if boo: print('!!!',falsecnt)
                    else:   print()
                continue

            excluded = all1
            def perebor(cur,fixed,excluded,depth):
                if debug>=0.5: nonlocal falsecnt
                if debug>=0.5: nonlocal maxdepth
                if debug>=0.5: maxdepth = max(maxdepth,depth)
                if debug>=d_main: print_sets2(cur,depth)
                
                # объединяем все множества выбранных строк
                union = 0
                for k,v in cur.items():
                    union |= v

                # по каждому элементу из этого множества
                q = 1
                while q<=union:
                    if q&union:
                        # по каждой из выбранных строк, в которой присутствует этот элемент
                        for k,v in cur.items():
                            if k>ln and v&q: # в предыдущие строки нам не нужно попадать
                                #фиксируем этот элемент, а остальные элементы из этой строки добавляем в исключённые
                                fixed2 = fixed|q
                                excluded2 = excluded&(all1^v^q)
                    #
                                cur2 = {}
                                cont = False
                                if debug>=d_main: sledstv = 0
                                for k2,v2 in cur.items():
                                    # из множеств удаляем вычеркнутые
                                    cur2[k2] = v2&excluded2
                                    # если есть пустые множества - конец
                                    if cur2[k2]==0:
                                        if debug>=d_main+0.5: print('    '*depth,sets(q),f'({k})','->',sets(cur2[k2]),f'>>> {k2} void')
                                        cont = True
                                        break
                                    # если есть множества из одного элемента - фиксируем их
                                    if count(cur2[k2])==1:
                                        if k2<=ln: # в предыдущие строки нам не нужно попадать
                                            if debug>=d_main+0.5: print('    '*depth,sets(q),f'({k})','->',sets(cur2[k2]),f'>>> {k2} already done')
                                            cont = True
                                            break
                                        fixed2|=cur2[k2]
                                        if debug>=d_main: sledstv |=cur2[k2]
                                if cont:
                                    continue
                    #                                        
                                #из выбранных строк исключаем те, в которых присутствуют выбранные элементы
                                cur2 = {k4:v4 for k4,v4 in cur2.items() if v4&fixed2==0}
                                if debug>=d_main: print('    '*depth,sets(q),f'({k})','->',sets(sledstv),'X',sets(v^q),'//',len(centrals),falsecnt)
                    #
                                # если строк не осталось - yield
                                if len(cur2)==0:
                                    fixed2 |= bit
                                    center = (matrix[ln]^bit)&fixed2
                                    if debug>=0.5: 
                                        boo = (fixed2,center) in centrals
                                        if boo: falsecnt+=1
                                    centrals.add((fixed2,center))
                                    if debug>=d_stat+0.5:
                                        print('    '*maxdepth,'+',pc(fixed2,center,W),f'[{len(centrals)}]',end=' ')
                                        if boo: print('!!!',falsecnt)
                                        else:   print()
                                    continue
                                #-> объединяем все множества выбранных строк
                                perebor(cur2,fixed2,excluded2,depth+1)
                            else:
                                if debug>=d_main+0.5: print('    '*depth,sets(q),f'({k})','->','>>> already done')
                    q<<=1
            perebor(cur,fixed,excluded,1)
    if debug>=d_stat: print('maxdepth:',maxdepth)
    if debug>=d_stat: print('falsecnt:',falsecnt)
    if debug>=0.5: return (cnt + len(centrals),falsecnt,centrals)
    return cnt + len(centrals)


# matrix incedence v2

In [14]:
import numpy as np

# я закономерность буду называть центральностью

# чтобы получить центральность необходимо в некоторой строке изменить один бит
# если строка x отличается от строки y одним битом, то изменением этого бита в строке x центральность получить невозможно
# центральность будем обозначать строкой, состоящей из '.', '0', '1' (точки и биты)
# при изменении любого бита (0<->1) в центральности мы должны получить паттерн (на строку), присутствующий в матрице
# если из строки x можно добраться в строку y изменив биты k,l, а строки x,y отличаются битами k,l,m_i, то биты m_i отсутствуют в центральности

# все множества не превышают 100 элементов, поэтому будем их хранить в целых числах как битовые множества

# матрица расстояний показывает, какие биты надо изменить, чтобы одна строка превратилась в другую
# в каждой строке пытемся изменить каждый бит
# найденные центральности складываем в общее множество
# далее алгоритм:
# 
# строку-бит задали (рассматриваем столбец в матрице расстояний, соответствующий данной строке. Он состоит из множеств)
# выбираем строки, в которых этот бит присутствует
#   в каждом множестве исключаем этот бит
# 
# среди выбранных
#   если есть пустые множества - конец (в эту строку можно добраться изменив только один бит)
#   если есть множества из одного элемента - фиксируем их (в эти строки можно добраться единственным способом)
#   из выбранных строк исключаем те, в которых присутствуют фиксированные элементы (они точно не равны центральности)
#   если строк не осталось - yield (найденные центральности складываем в общее множество)
# 
#   объединяем все множества выбранных строк
#   + подсчитываем, сколько раз встречается каждый элемент, и перебираем от меньшего к большему
#   по каждому элементу из этого множества
#       выбранные строки разбиваем на текущие (те, в которых присутствуют этот элемент (они точно не равны центральности)), и дальнейшие (для дальнейшего анализа)
#       если все текущие строки ранее обрабатывались - continue
#       пересекаем текущие строки
#       фиксируем этот элемент, а остальные элементы из пересечения добавляем в исключённые (точно должны отсутствовать в центральности)
#       из дальнейших множеств удаляем исключённые

#       если есть пустые множества - конец (в эту строку можно добраться изменив только один бит)
#       если есть множества из одного элемента - фиксируем их (в эти строки можно добраться единственным способом)
#       из выбранных строк исключаем те, в которых присутствуют фиксированные элементы (они точно не равны центральности)

#       если дальнейших строк не осталось - yield (найденные центральности складываем в общее множество)
#       по каждой из текущих строк, которые раньше не обрабатывали
#           остальные элементы из этой строки добавляем в исключённые (точно должны отсутствовать в центральности)
#           из дальнейших множеств удаляем исключённые
# 
#           если есть пустые множества - конец (в эту строку можно добраться изменив только один бит)
#           если есть множества из одного элемента - фиксируем их (в эти строки можно добраться единственным способом)
#           из выбранных строк исключаем те, в которых присутствуют выбранные элементы (они точно не равны центральности)
# 
#           если строк не осталось - yield (найденные центральности складываем в общее множество)
#           -> объединяем все множества выбранных строк (рекурсия)
#       из выбранных строк исключаем этот элемент (он полностью обработан)
#       если есть пустые строки - конец
# 
# + в алгоритм добавляем опитимизации, чтобы он не пытался добраться из текущей строки в ранее полностью рассмотренные
# ответ - размер общего множества центральностей + количество постоянных столбцов (которые мы в самом начале исключили)

from inspect import getframeinfo, stack

def thisline():
    caller = getframeinfo(stack()[1][0])
    return caller.lineno

def bits(x,l):
    s = ''
    for i in range(l):
        s+= '1' if (2**i)&x else '0'
    return s
def sets(x):
    se = set()
    i=0
    q=1
    while q<=x:
        if q&x:
            se.add(i)
        i+=1
        q<<=1
    return ''.join(str(i) for i in sorted(list(se)))
0.5 # статистику считать но не печатать
d_stat = 1 # 1 статистика
1.5 # только добавления
d_main = 2 # 2 основное
2.5 # + ускорения (пропуски)
d_dbg = 3 # 3 отладка
debug = 0
def printmat(m):
    ml = 0
    for i in range(len(m)):
        for j in range(len(m[i])):
            ml = max(ml,len(sets(m[i][j])))
    f = '{:'+str(ml)+'}'
    for i in range(len(m)):
        for j in range(len(m[i])):
            print(f.format(sets(m[i][j])),end=' ')
        print()
def print_sets(sets,depth=0,mes=None):
    if mes!=None:
        print('    '*depth,mes)
    union = 0
    for s in sets:
        union|= s
    se = set()
    i=0
    q=1
    while q<=union:
        if q&union:
            se.add(i)
        i+=1
        q<<=1
    se = sorted(list(se))
    for s,n in sets.items():
        print('    '*depth,f'|{n:2})',end=' ')
        for i in se:
            print(i if (2**i)&s else ' ' if i<10 else '  ',end=' ')
        print()


def pc(fixed,center,W):
    fixed = bits(fixed,W)
    center = bits(center,W)
    s = ''
    for i in range(len(fixed)):
        s+= '.' if fixed[i]=='0' else center[i]
    return s
def number_of_patterns(matrix1: np.ndarray) -> int:
    # одинаковые строки убираем сразу
    # постоянные столбцы обрабатываем отдельно и убираем
    if debug>=d_main: print('start')
    if debug>=d_main: print(matrix1)
    cnt = 0
    W = len(matrix1[0])
    H = len(matrix1)
    # ищем постоянные столбцы
    matrix = [[] for i in range(H)]
    for i in range(W):
        if (matrix1[:,i]==1).all() or (matrix1[:,i]==0).all():
            cnt+=1
        else:
            for j in range(H):
                matrix[j].append(matrix1[j,i])
    W-=cnt
    if debug>=d_main: print('постоянных столбцов: ',cnt)
    
    # преобразовываем в биты
    for i in range(H):
        q=1
        line = 0
        for j in range(W):
            if matrix[i][j]:
                line|=q
            q<<=1
        matrix[i] = line
    all1 = 2**(W+1)-1

    # удаляем повторы
    matrix.sort()
    for i in range(H-2,-1,-1):
        if matrix[i]==matrix[i+1]:
            del matrix[i+1]
            H-=1
    if debug>=d_main: 
        print('подготовили матрицу',H,W,'--',thisline())
        for x in matrix:
            print(bits(x,W))

    dist = []
    for i in range(H):
        dist.append([])
        for j in range(H):
            dist[i].append(matrix[i]^matrix[j])
    if debug>=d_stat+0.5: 
        print('матрица расстояний')
        printmat(dist)
    def count(x):
        q = 1
        cnt = 0
        while q<=x:
            if q&x:
                cnt+=1
            q<<=1
        return cnt
    centrals = set()
    maxdepth = 0
    falsecnt = 0
    for ln in range(H):
        if debug>=d_stat+0.5: print('---------',ln,'--------','//',len(centrals),falsecnt)
        for bn in range(W):
            bit = 2**bn
            # строку-бит задали

            # выбираем строки, в которых этот бит присутствует
            cont = False
            fixed = 0
            for i in range(H):
                if dist[ln][i]&bit:
                    # в каждом множестве исключаем этот бит
                    tmp = dist[ln][i]^bit
                    # среди выбранных:
                    # если есть пустые множества - конец
                    if tmp==0:
                        if debug>=d_main+0.5: print(bn,'->',f'>>> {ln} void','--',thisline())
                        cont = True
                        break
                    # если есть множества из одного элемента - фиксируем их
                    if count(tmp)==1:
                        if i<=ln: # в предыдущие строки нам не нужно попадать
                            if debug>=d_main+0.5: print(bn,'->',f'>>> {i} already done','--',thisline())
                            cont = True
                            break
                        fixed|=tmp
            if cont:
                continue

            # из выбранных строк исключаем те, в которых присутствуют фиксированные элементы
            cur = {}
            for i in range(H):
                if dist[ln][i]&bit and dist[ln][i]&fixed==0:
                    v = dist[ln][i]^bit
                    cur[v] = i # еще ничего не вычеркнул => все строки разные
            if debug>=d_stat+0.5: print(bn,'->',sets(fixed),'//',len(centrals),falsecnt)

            #если строк не осталось - yield
            if len(cur)==0:
                fixed |= bit
                center = (matrix[ln]^bit)&fixed
                if debug>=0.5: 
                    boo = (fixed,center) in centrals
                    if boo: falsecnt+=1
                centrals.add((fixed,center))

                if debug>=d_stat+0.5:
                    print('+',pc(fixed,center,W),f'[{len(centrals)}]',end=' ')
                    if boo: print('!!!',falsecnt)
                    else:   print()
                continue

            excluded = all1
            def perebor(sel,fixed,excluded,depth):
                if debug>=0.5: nonlocal falsecnt
                if debug>=0.5: nonlocal maxdepth
                if debug>=0.5: maxdepth = max(maxdepth,depth)
                if debug>=d_main: print('    '*depth,f'fixed={sets(fixed)}, excluded={sets(all1^excluded)}','--',thisline())
                
                # объединяем все множества выбранных строк
                union = 0
                for v in sel:
                    union |= v

#   + подсчитываем, сколько раз встречается каждый элемент, и перебираем от меньшего к большему

                # по каждому элементу из этого множества
                q = 1
                while q<=union:
                    if q&union:
                        if debug>=d_main: print_sets(sel,depth,f'sel: bit {sets(q)} -- {thisline()}')
                        # выбранные строки разбиваем на текущие (те, в которых присутствуют этот элемент (они точно не равны центральности)), и дальнейшие (для дальнейшего анализа)
                        cur = {}
                        intersect = -1
                        cont = True
                        partial_done = False
                        for s,n, in sel.items():
                            if q&s:
                                cur[s] = n
                                # если все текущие строки ранее обрабатывались - continue
                                if n>ln:
                                    cont = False
                                else:
                                    partial_done = True
                                # пересекаем текущие строки
                                if intersect==-1:
                                    intersect = s
                                else:
                                    intersect &= s
                        if cont:
                            if debug>=d_main+0.5: print('    '*depth,sets(q),'->','>>> all already done','--',thisline())
                    #
                        if not cont:
                            # фиксируем этот элемент, а остальные элементы из пересечения добавляем в исключённые (точно должны отсутствовать в центральности)
                            fixed2 = fixed|q
                            excluded2 = excluded&(all1^intersect^q)
                            if debug>=d_dbg: print('    '*depth,f'fixed2={sets(fixed2)}, excluded2={sets(all1^excluded2)}','--',thisline())
                            if debug>=d_dbg: print_sets(cur,depth,f'cur: -- {thisline()}')
                    #
                            # из дальнейших множеств удаляем исключённые
                            fur = {}
                            cont = False
                            if debug>=d_main: sledstv = 0
                            for s,n, in sel.items():
                                if q&s==0:
                                    v = s&excluded2
                                    # если есть пустые множества - конец (в эту строку можно добраться изменив только один бит)
                                    if v==0:
                                        if debug>=d_main+0.5: print('    '*depth,sets(q),'->',f'>>> {n} void','--',thisline())
                                        cont = True
                                        break
                                    if v in fur:
                                        fur[v] = max(fur[v],n)
                                    else:
                                        fur[v] = n
                        if not cont:
                            # из выбранных строк исключаем те, в которых присутствуют фиксированные элементы (они точно не равны центральности)
                            fur = {s:n for s,n in fur.items() if s&fixed2==0}
                            if debug>=d_dbg: print_sets(fur,depth,f'fur: -- {thisline()}')
                    #
                            if debug>=d_main: print('    '*depth,sets(q),'X',sets(intersect^q),'->',sets(sledstv),'//',len(centrals),falsecnt,'--',thisline())
                            # если дальнейших строк не осталось - yield (найденные центральности складываем в общее множество)
                            if len(fur)==0:
                                if not partial_done:
                                    fixed2 |= bit
                                    center = (matrix[ln]^bit)&fixed2
                                    if debug>=0.5: 
                                        boo = (fixed2,center) in centrals
                                        if boo: falsecnt+=1
                                    centrals.add((fixed2,center))
                                    if debug>=d_stat+0.5:
                                        print('    '*maxdepth,'+',pc(fixed2,center,W),f'[{len(centrals)}]',end=' ')
                                        if boo: print('!!!',falsecnt)
                                        else:   print()
                                else:
                                    if debug>=d_main+0.5: print('    '*maxdepth,f'+ >>>','--',thisline())
                                cont = True
                    #
                        if not cont:
                            # по каждой из выбранных строк, в которой присутствует этот элемент
                            for v,k in cur.items():
                                if k>ln: # в предыдущие строки нам не нужно попадать
                                    # остальные элементы из этой строки добавляем в исключённые (точно должны отсутствовать в центральности)
                                    excluded3 = excluded2&(all1^v^q)
                                    if debug>=d_main and v==intersect: print('    '*depth,' ','частное равно общему','--',thisline())
                    #
                                    cont = False
                                    fixed3 = fixed2
                                    for v2,k2 in fur.items():
                                        # из множеств удаляем вычеркнутые
                                        t = v2&excluded3
                                        # если есть пустые множества - конец
                                        if t==0:
                                            if debug>=d_main+0.5: print('    '*depth,' ',sets(q),f'({k})','->',sets(t),f'>>> {k2} void','--',thisline())
                                            cont = True
                                            break
                                        # если есть множества из одного элемента - фиксируем их
                                        if count(t)==1:
                                            if k2<=ln: # в предыдущие строки нам не нужно попадать
                                                if debug>=d_main+0.5: print('    '*depth,sets(q),f'({k})','->',sets(t),f'>>> {k2} already done','--',thisline())
                                                cont = True
                                                break
                                            fixed3|=t
                                    if cont:
                                        continue
                                    if debug>=d_dbg: print('    '*depth,' ',f'fixed3={sets(fixed3)}, excluded3={sets(all1^excluded3)}','--',thisline())
                    #                                    
                                    #из выбранных строк исключаем те, в которых присутствуют выбранные элементы
                                    cur2 = {}
                                    for v2,k2 in fur.items():
                                        if v2&excluded3&fixed3==0:
                                            t = v2&excluded3
                                            if t in cur2:
                                                cur2[t] = max(cur2[t],k2)
                                            else:
                                                cur2[t] = k2
                                    if debug>=d_dbg: print_sets(cur2,depth,f'cur2: -- {thisline()}')
                    #
                                    if debug>=d_main: print('    '*depth,' ',sets(q),f'({k})','X',sets(excluded3^excluded2),'->',sets(fixed3^fixed2),'//',len(centrals),falsecnt,'--',thisline())
                                    # если строк не осталось - yield
                                    if len(cur2)==0:
                                        fixed3 |= bit
                                        center = (matrix[ln]^bit)&fixed3
                                        if debug>=0.5: 
                                            boo = (fixed3,center) in centrals
                                            if boo: falsecnt+=1
                                        centrals.add((fixed3,center))
                                        if debug>=d_stat+0.5:
                                            print('    '*maxdepth,' ','+',pc(fixed3,center,W),f'[{len(centrals)}]',end=' ')
                                            if boo: print('!!!',falsecnt)
                                            else:   print()
                                        continue
                                    #-> объединяем все множества выбранных строк
                                    perebor(cur2,fixed3,excluded3,depth+1)
                                else:
                                    if debug>=d_main+0.5: print('    '*depth,' ',sets(q),f'({k})','->','>>> already done','--',thisline())
                    #
                        # из выбранных строк исключаем этот элемент (он полностью обработан)
                        sel2 = {}
                        cont = False
                        for v,k in sel.items():
                            t = v&(all1^q)
                            # если есть пустые строки - конец
                            if t==0:
                                if debug>=d_main+0.5: print('    '*depth,f'>>> deletion {sets(q)} make {k} void','--',thisline())
                                cont = True
                                break
                            if t in sel2:
                                sel2[t] = max(sel2[t],k)
                            else:
                                sel2[t] = k
                        if cont:
                            q<<=1
                            return
                        sel = sel2
                    q<<=1
            perebor(cur,fixed,excluded,1)
    if debug>=d_stat: print('maxdepth:',maxdepth)
    if debug>=d_stat: print('falsecnt:',falsecnt)
    if debug>=0.5: return (cnt + len(centrals),falsecnt,centrals)
    return cnt + len(centrals)



# тесты

In [24]:
debug = 0.5
W=5
n = 2**W
base=[x for x in range(n)]
for H in range(1,min(n,100)+1):
    print(H,'-------')
    res=[-1 for x in range(H)]
    fcnt1=-1
    fcnt2=-1
    for res in subsets(base,H,res):
        #print(res,':')
        m = np.empty((H,W),dtype=np.int32)
        for i in range(H):
            for j in range(W):
                m[i,j] = 1 if 2**j & res[i] else 0
        r1,f1,s1 = number_of_patterns(m)
        r2,f2,s2 = number_of_patterns2(m)
        if r1!=r2:
            print(m,'fail')
        if f1>fcnt1:
            fcnt1 = f1
            m1 = m
        if f2>fcnt2:
            fcnt2 = f2
            m2 = m
    print('1:',fcnt1)
    print(m1)
    print('2:',fcnt2)
    print(m2)
print('finished')

1 -------
1: 0
[[0 0 0 0 0]]
2: 0
[[0 0 0 0 0]]
2 -------
1: 0
[[0 0 0 0 0]
 [1 0 0 0 0]]
2: 0
[[0 0 0 0 0]
 [1 0 0 0 0]]
3 -------
1: 12
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 1 1 1]]
2: 12
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 1 1 1]]
4 -------


KeyboardInterrupt: 

In [25]:
debug = d_main+0.5
m=np.array(
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 1, 1, 1, 0],
 [0, 1, 1, 0, 1],
 [1, 1, 0, 1, 1],
 [1, 0, 1, 1, 1]])
number_of_patterns(m)

start
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 0 1]
 [1 1 0 1 1]
 [1 0 1 1 1]]
постоянных столбцов:  0
подготовили матрицу 6 5 -- 162
00000
10000
01110
01101
11011
10111
матрица расстояний
     0    123  124  0134 0234 
0         0123 0124 134  234  
123  0123      34   024  014  
124  0124 34        023  013  
0134 134  024  023       12   
0234 234  014  013  12        
--------- 0 -------- // 0 0
0 -> >>> 0 void -- 201
1 ->  // 0 0
     fixed=, excluded= -- 242
     sel: bit 0 -- 255
     | 2)   2 3   
     | 3)   2   4 
     | 4) 0   3 4 
     0 X 34 ->  // 0 0 -- 305
       частное равно общему -- 329
       0 (4) X  -> 2 // 0 0 -- 363
       + 010.. [1] 
     sel: bit 2 -- 255
     | 2) 2 3   
     | 3) 2   4 
     | 4)   3 4 
     2 X  ->  // 1 0 -- 305
       2 (2) X 3 -> 4 // 1 0 -- 363
       + .10.0 [2] 
       2 (3) X 4 -> 3 // 2 0 -- 363
       + .100. [3] 
     sel: bit 3 -- 255
     | 2) 3   
     | 3)   4 
     | 4) 3 4 
     3 X  ->  // 3 0 -- 305
       частное 

(27,
 13,
 {(7, 2),
  (7, 4),
  (7, 7),
  (11, 3),
  (11, 8),
  (13, 5),
  (13, 8),
  (14, 2),
  (14, 4),
  (14, 8),
  (19, 3),
  (19, 16),
  (21, 5),
  (21, 16),
  (22, 2),
  (22, 4),
  (22, 16),
  (25, 9),
  (25, 17),
  (25, 24),
  (26, 2),
  (26, 8),
  (26, 16),
  (28, 4),
  (28, 8),
  (28, 16),
  (30, 30)})

In [26]:
number_of_patterns2(m)

постоянных столбцов:  0
подготовили матрицу 6 5
00000
10000
01110
01101
11011
10111
матрица расстояний
     0    123  124  0134 0234 
0         0123 0124 134  234  
123  0123      34   024  014  
124  0124 34        023  013  
0134 134  024  023       12   
0234 234  014  013  12        
--------- 0 -------- // 0 0
0 -> >>> 0 void
1 ->  // 0 0
      2 )   2 3   
      3 )   2   4 
      4 ) 0   3 4 
     0 (2) -> >>> already done
     0 (3) -> >>> already done
     0 (4) -> 02 X 34 // 0 0
     + 010.. [1] 
     2 (2) -> 2 X 3 // 1 0
          4 ) 0 4 
         0 (4) -> 0 X 4 // 1 0
         + 010.. [1] !!! 1
         4 (4) -> 4 X 0 // 1 1
         + .10.0 [2] 
     2 (3) -> 2 X 4 // 2 1
          4 ) 0 3 
         0 (4) -> 0 X 3 // 2 1
         + 010.. [2] !!! 2
         3 (4) -> 3 X 0 // 2 2
         + .100. [3] 
     2 (4) -> >>> already done
     3 (2) -> 34 X 2 // 3 2
         + .1.00 [4] 
     3 (3) -> >>> already done
     3 (4) -> 23 X 04 // 4 2
         + .100. [4] !!! 3
     4

(27,
 57,
 {(7, 2),
  (7, 4),
  (7, 7),
  (11, 3),
  (11, 8),
  (13, 5),
  (13, 8),
  (14, 2),
  (14, 4),
  (14, 8),
  (19, 3),
  (19, 16),
  (21, 5),
  (21, 16),
  (22, 2),
  (22, 4),
  (22, 16),
  (25, 9),
  (25, 17),
  (25, 24),
  (26, 2),
  (26, 8),
  (26, 16),
  (28, 4),
  (28, 8),
  (28, 16),
  (30, 30)})

In [27]:
number_of_patterns1(np.array(
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 1, 1, 1, 0],
 [0, 1, 0, 0, 1],
 [1, 1, 0, 0, 1]]))

12

In [28]:
debug=d_stat
H = W = 20
m = np.empty((H,W),dtype=np.int32)
for i in range(H):
    for j in range(W):
        m[i,j] = np.random.randint(2)
x1,y1,s1 = number_of_patterns(m)
x2,y2,s2 = number_of_patterns2(m)
print(x1)
if x1!=x2:
    print('fail')
    m1 = m

maxdepth: 5
falsecnt: 29525
maxdepth: 5
falsecnt: 572855
11071


In [29]:

H = W = 8
m = np.empty((H,W),dtype=np.int32)
for i in range(H):
    for j in range(W):
        m[i,j] = np.random.randint(2)

In [30]:
debug=d_main+0.5
x1,y1,s1 = number_of_patterns(m)
#x2,y2,s2 = number_of_patterns2(m)
print(x1)

start
[[1 1 0 0 1 1 0 0]
 [1 0 1 1 0 1 0 1]
 [1 0 0 1 0 0 0 1]
 [1 0 1 1 1 1 1 0]
 [1 0 1 1 1 1 1 1]
 [0 1 0 0 0 1 1 0]
 [0 1 1 1 0 1 0 0]
 [1 1 1 0 1 1 0 0]]
постоянных столбцов:  0
подготовили матрицу 8 8 -- 162
01110100
11001100
11101100
01000110
10111110
10010001
10110101
10111111
матрица расстояний
       0234   034    236    0146   01257  017    01467  
0234          2      046    1236   13457  12347  12367  
034    2             0246   136    123457 1347   1367   
236    046    0246          01234  013567 012367 012347 
0146   1236   136    01234         24567  467    7      
01257  13457  123457 013567 24567         25     2456   
017    12347  1347   012367 467    25            46     
01467  12367  1367   012347 7      2456   46            
--------- 0 -------- // 0 0
0 ->  // 0 0
     fixed=, excluded= -- 242
     sel: bit 1 -- 255
     | 1)   2 3 4       
     | 2)     3 4       
     | 4) 1     4   6   
     | 5) 1 2     5   7 
     | 6) 1           7 
     | 7) 1     4   

In [31]:
debug=d_stat+0.5
number_of_patterns(m)

матрица расстояний
       0234   034    236    0146   01257  017    01467  
0234          2      046    1236   13457  12347  12367  
034    2             0246   136    123457 1347   1367   
236    046    0246          01234  013567 012367 012347 
0146   1236   136    01234         24567  467    7      
01257  13457  123457 013567 24567         25     2456   
017    12347  1347   012367 467    25            46     
01467  12367  1367   012347 7      2456   46            
--------- 0 -------- // 0 0
0 ->  // 0 0
       + 11.1.... [1] 
         + 11.1.... [1] !!! 1
         + 11..0... [2] 
         + 11.1.... [2] !!! 2
         + 11..0... [2] !!! 3
           + 11.1.... [2] !!! 4
           + 1..1..00 [3] 
           + 1...0..0 [4] 
           + 1...0..0 [4] !!! 5
1 ->  // 4 5
         + 00...... [5] 
           + .0..0..0 [6] 
           + .0....00 [7] 
2 ->  // 7 5
           + 0.0...0. [8] 
         + 0.01.... [9] 
         + 0.0...0. [9] !!! 6
         + .101.... [10] 
           + .1

(62,
 97,
 {(3, 0),
  (10, 0),
  (11, 11),
  (13, 4),
  (13, 8),
  (14, 10),
  (17, 16),
  (19, 3),
  (22, 16),
  (25, 1),
  (26, 26),
  (28, 4),
  (28, 24),
  (33, 0),
  (34, 2),
  (36, 4),
  (38, 32),
  (40, 0),
  (44, 40),
  (48, 16),
  (53, 33),
  (67, 67),
  (69, 0),
  (69, 65),
  (69, 68),
  (70, 64),
  (70, 70),
  (73, 0),
  (73, 65),
  (73, 72),
  (74, 74),
  (76, 68),
  (76, 72),
  (81, 65),
  (82, 16),
  (82, 64),
  (82, 82),
  (84, 68),
  (84, 80),
  (86, 2),
  (88, 0),
  (88, 24),
  (88, 72),
  (88, 80),
  (96, 64),
  (116, 32),
  (129, 128),
  (130, 130),
  (134, 0),
  (136, 128),
  (140, 8),
  (145, 1),
  (146, 0),
  (148, 144),
  (160, 0),
  (164, 160),
  (194, 0),
  (196, 192),
  (201, 9),
  (208, 144),
  (208, 192),
  (212, 0)})

In [23]:
m1

NameError: name 'm1' is not defined

In [ ]:
debug = d_stat
n1,f1,c1 = number_of_patterns(m1)
n1

In [ ]:
n2,f2,c2 = number_of_patterns2(m1)
n2

In [ ]:
number_of_patterns1(m1)

In [ ]:
for fixed,mask in c1-c2:
    print(pc(fixed,mask,10))
print('---')
for fixed,mask in c2-c1:
    print(pc(fixed,mask,10))